version: '3.1'
services:
  ms-sql:
    image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
    # image: custom-sql:lastest
    container_name: ms-sql
    volumes:
      - sqlvolume:/var/opt/mssql 
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: p3dc68f2Q@#
      MSSQL_AGENT_ENABLED: 1

    ports:
      - 1433:1433 
volumes:
  sqlvolume:
#networks: 
#  default: 
#    external: 
#      name: db-network